// lib/data.js — Central data store for the entire portfolio

export const personalInfo = {
  name: "Mohamed Abobakr",
  title: "MERN Stack Developer",
  tagline: "I build digital products that convert visitors into clients.",
  bio: "I'm a full-stack developer obsessed with building high-performance, beautiful web applications. With 3+ years and 30+ shipped projects, I turn complex ideas into clean, scalable products. I don't just write code — I engineer solutions that grow businesses.",
  location: "Cairo, Egypt · Available Worldwide",
  email: "mohamed.dev.m@gmail.com",
  availability: "Open to Projects",
  experience: "1+ Years",
  projects: "30+",
  clients: "20+",
  social: {
    github: "https://github.com/MohamedAbobakr12",
    linkedin: "https://linkedin.com/in/mohamed-abobakr-9b83551b2",
    twitter: "https://twitter.com",
    facebook: "https://facebook.com/m.hame.abo.bakr",
    whatsapp: "https://wa.me/+201119452390",
  },
}

export const skills = [
  { name: "React.js", level: 95, category: "frontend", icon: "⚛️" },
  { name: "Next.js", level: 92, category: "frontend", icon: "▲" },
  { name: "Node.js", level: 90, category: "backend", icon: "🟢" },
  { name: "Express.js", level: 88, category: "backend", icon: "🚀" },
  { name: "MongoDB", level: 85, category: "database", icon: "🍃" },
  { name: "TypeScript", level: 82, category: "language", icon: "🔷" },
  { name: "JavaScript", level: 97, category: "language", icon: "🟡" },
  { name: "Tailwind CSS", level: 93, category: "frontend", icon: "🎨" },
  { name: "PostgreSQL", level: 75, category: "database", icon: "🐘" },
  { name: "Redis", level: 70, category: "database", icon: "🔴" },
  { name: "Docker", level: 72, category: "devops", icon: "🐳" },
  { name: "AWS", level: 68, category: "devops", icon: "☁️" },
  { name: "GraphQL", level: 78, category: "backend", icon: "🔺" },
  { name: "REST APIs", level: 94, category: "backend", icon: "🔗" },
  { name: "Git & GitHub", level: 92, category: "tools", icon: "🐙" },
  { name: "Figma", level: 74, category: "tools", icon: "🎭" },
]

export const projects = [
  {
    id: 1,
    title: "Henry Clark - Portfolio",
    description: "A sleek personal portfolio website showcasing projects, skills, and experience with an elegant design and smooth user interactions.",
    image: "https://res.cloudinary.com/dj0deiybu/image/upload/v1774290978/Thumbnail_cthiwf.jpg",
    tags: ["Vite", "React", "JavaScript", "TailwindCSS"],
    platform: "web",
    type: "frontend",
    liveUrl: "https://portfolio-hc-app.vercel.app/",
    githubUrl: "https://github.com/MohamedAbobakr12/Portfolio",
    featured: true,
    stats: { projects: "10+", skills: "15+", responsive: "100%" },
  },
  {
    id: 2,
    title: "Xora | SaaS Landing Page",
    description: "A modern, fully responsive SaaS landing page featuring smooth animations, clean UI components, and a professional layout designed to showcase product features and drive user conversions.",
    image: "https://res.cloudinary.com/dj0deiybu/image/upload/v1774285742/Thumbnail_ah3fpw.jpg",
    tags: ["Vite", "React", "JavaScript", "TailwindCSS"],
    platform: "web",
    type: "frontend",
    liveUrl: "https://xora-app.vercel.app/",
    githubUrl: "https://github.com/MohamedAbobakr12/Xora",
    featured: true,
    stats: { sections: "10+", animations: "Smooth", responsive: "100%" },
  },
  {
    id: 3,
    title: "Space Portfolio",
    description: "A visually immersive fullstack developer portfolio built with Next.js, featuring a space-themed design, animated UI, and a comprehensive showcase of skills spanning frontend, backend, mobile, and DevOps technologies.",
    image: "https://res.cloudinary.com/dj0deiybu/image/upload/v1774291838/Thumbnail_gereei.jpg",
    tags: ["Next.js", "React", "TypeScript", "TailwindCSS"],
    platform: "web",
    type: "frontend",
    liveUrl: "https://space-portfolio-next.vercel.app/",
    githubUrl: "https://github.com/MohamedAbobakr12/Space-Portfolio",
    featured: true,
    stats: { skills: "20+", projects: "3+", stack: "Fullstack" },
  },
  {
    id: 4,
    title: "Nike",
    description: "A pixel-perfect Nike landing page clone built with a modern frontend stack, featuring a clean product showcase, responsive design, and smooth UI interactions inspired by Nike's official brand aesthetic.",
    image: "https://res.cloudinary.com/dj0deiybu/image/upload/v1774292734/Thumbnail_q0ixzl.jpg",
    tags: ["Vite", "React", "JavaScript", "TailwindCSS"],
    platform: "web",
    type: "frontend",
    liveUrl: "https://nike-three-virid.vercel.app/",
    githubUrl: "https://github.com/MohamedAbobakr12/Nike",
    featured: false,
    stats: { doctors: "200+", patients: "3K+", calls: "50K+" },
  },
  {
    id: 5,
    title: "E-Commerce Bike",
    description: "A fully responsive e-commerce bike store featuring product showcases, categories, accessories, and a modern UI with smooth navigation built for cycling enthusiasts.",
    image: "https://res.cloudinary.com/dj0deiybu/image/upload/v1774294632/Thumbnail_nkrjxh.jpg",
    tags: ["Next.js", "React", "JavaScript", "TailwindCSS"],
    platform: "web",
    type: "frontend",
    liveUrl: "https://e-bike-rose.vercel.app/",
    githubUrl: "https://github.com/MohamedAbobakr12/E-Bike",
    featured: false,
    stats: { products: "20+", categories: "4+", speed: "45 KM/H" },
  },
  {
    id: 6,
    title: "Hubble - Landing Page SaaS",
    description: "A professional SaaS landing page for an ecommerce management platform, featuring CRM highlights, client testimonials, team section, blog, and FAQ — all wrapped in a clean and modern UI.",
    image: "https://res.cloudinary.com/dj0deiybu/image/upload/v1774296717/Thumbnail_nvutft.jpg",
    tags: ["Next.js", "React", "JavaScript", "TailwindCSS"],
    platform: "web",
    type: "frontend",
    liveUrl: "https://hubble-puce.vercel.app/",
    githubUrl: "https://github.com/MohamedAbobakr12/Hubble",
    featured: false,
    stats: { companies: "100+", integrations: "10+", sections: "8+" },
  },
  {
    id: 7,
    title: "Crypto App",
    description: "A modern crypto investment platform landing page featuring token listings, pricing plans, team section, and partner integrations — designed to build trust and drive user onboarding in the crypto space.",
    image: "https://res.cloudinary.com/dj0deiybu/image/upload/v1774303062/Thumbnail_ct1sjy.jpg",
    tags: ["Next.js", "React", "JavaScript", "TailwindCSS"],
    platform: "web",
    type: "frontend",
    liveUrl: "https://crypto-app-beta-lemon.vercel.app/",
    githubUrl: "https://github.com/MohamedAbobakr12/Crypto-App",
    featured: false,
    stats: { tokens: "128+", partners: "5+", plans: "3" },
  },
  {
    id: 8,
    title: "Movies App",
    description: "A dynamic movie discovery app powered by a live movies API, featuring trending movies, real-time search, ratings, and a sleek dark-themed UI for an immersive browsing experience.",
    image: "https://res.cloudinary.com/dj0deiybu/image/upload/v1774311964/Thumbnail_smnvph.jpg",
    tags: ["Vite", "React", "JavaScript", "TailwindCSS"],
    platform: "web",
    type: "frontend",
    liveUrl: "https://movies-app-live.vercel.app/",
    githubUrl: "https://github.com/MohamedAbobakr12/Movie-App",
    featured: false,
    stats: { movies: "1000+", trending: "Real-time", search: "Instant" },
  },
]

export const experience = [
  {
    year: "2024 – Present",
    role: "Senior MERN Stack Developer",
    company: "Freelance · Remote",
    description: "Building end-to-end web applications for clients worldwide. Delivered 15+ projects with a 100% client satisfaction rate.",
    skills: ["React", "Node.js", "MongoDB", "AWS"],
    type: "work",
  },
  {
    year: "2022 – 2024",
    role: "Full-Stack Developer",
    company: "TechNova Agency",
    description: "Led development of 3 SaaS products from scratch. Mentored junior devs and established code review processes.",
    skills: ["Next.js", "Express", "PostgreSQL"],
    type: "work",
  },
  {
    year: "2021 – 2022",
    role: "Frontend Developer",
    company: "StartupHub",
    description: "Built pixel-perfect UIs from Figma designs, optimized performance by 60%, and shipped features weekly.",
    skills: ["React", "JavaScript", "CSS"],
    type: "work",
  },
  {
    year: "2021",
    role: "B.Sc. Computer Science",
    company: "Cairo University",
    description: "Graduated with honors. Built a final year project — a distributed task management system used by 500+ students.",
    skills: ["Algorithms", "Databases", "OS"],
    type: "education",
  },
]

export const blogPosts = [
  {
    id: 1,
    title: "Building Scalable Node.js APIs: Patterns I Use in Production",
    excerpt: "After building 30+ APIs, I've collected battle-tested patterns for structuring Node.js backends that scale without headaches.",
    category: "Backend",
    readTime: "8 min",
    date: "Jun 10, 2025",
    slug: "scalable-nodejs-apis",
    image: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=400&h=250&fit=crop",
  },
  {
    id: 2,
    title: "Why I Switched from REST to GraphQL (and Back Again)",
    excerpt: "My honest experience after using GraphQL in 5 production projects — when it shines, when it fails, and when REST is just better.",
    category: "Architecture",
    readTime: "6 min",
    date: "May 22, 2025",
    slug: "graphql-vs-rest",
    image: "https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=400&h=250&fit=crop",
  },
  {
    id: 3,
    title: "How I Land $5K+ Freelance Projects Consistently",
    excerpt: "The exact system I use to attract high-value clients, write proposals that win, and deliver projects that generate referrals.",
    category: "Business",
    readTime: "10 min",
    date: "May 5, 2025",
    slug: "landing-freelance-projects",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=250&fit=crop",
  },
]

export const services = [
  {
    title: "Full-Stack Web Apps",
    description: "End-to-end MERN stack applications, from database design to deployment.",
    icon: "🖥️",
    price: "From $3,000",
  },
  {
    title: "API Development",
    description: "Scalable REST or GraphQL APIs with authentication, rate limiting, and docs.",
    icon: "🔌",
    price: "From $1,500",
  },
  {
    title: "Performance Optimization",
    description: "Speed audit and optimization for existing React or Node.js applications.",
    icon: "⚡",
    price: "From $800",
  },
  {
    title: "SaaS Development",
    description: "Complete SaaS platforms with subscriptions, dashboards, and multi-tenancy.",
    icon: "🚀",
    price: "From $8,000",
  },
]

export const testimonials = [
  {
    name: "Sarah Johnson",
    role: "CEO, StyleHive",
    text: "Alex delivered our e-commerce platform in 6 weeks. Sales went up 40% after launch. Will definitely hire again.",
    avatar: "SJ",
    rating: 5,
  },
  {
    name: "Marcus Chen",
    role: "CTO, DevFlow Inc",
    text: "Clean code, clear communication, zero bugs. The API Alex built handles 2M requests/day without breaking a sweat.",
    avatar: "MC",
    rating: 5,
  },
  {
    name: "Amira Hassan",
    role: "Founder, EduSpark",
    text: "Our learning platform went from idea to 5,000 users in 3 months. Alex was instrumental in that journey.",
    avatar: "AH",
    rating: 5,
  },
]
