// lib/data.js — Central data store for the entire portfolio

export const personalInfo = {
  name: "Mohamed Abobakr",
  title: "MERN Stack Developer",
  tagline: "I build digital products that convert visitors into clients.",
  bio: "I'm a full-stack developer obsessed with building high-performance, beautiful web applications. With 3+ years and 30+ shipped projects, I turn complex ideas into clean, scalable products. I don't just write code — I engineer solutions that grow businesses.",
  location: "Cairo, Egypt · Available Worldwide",
  email: "mohamed.dev.m@gmail.com",
  availability: "Open to Projects",
  experience: "1+ Years",
  projects: "30+",
  clients: "20+",
  social: {
    github: "https://github.com/MohamedAbobakr12",
    linkedin: "https://linkedin.com/in/mohamed-abobakr-9b83551b2",
    twitter: "https://twitter.com",
    facebook: "https://facebook.com/m.hame.abo.bakr",
    whatsapp: "https://wa.me/+201119452390",
  },
}

export const skills = [
  { name: "React.js", badge: "Expert", category: "frontend", icon: "⚛️" },
  { name: "Next.js", badge: "Expert", category: "frontend", icon: "▲" },
  { name: "Node.js", badge: "Expert", category: "backend", icon: "🟢" },
  { name: "Express.js", badge: "Advanced", category: "backend", icon: "🚀" },
  { name: "MongoDB", badge: "Advanced", category: "database", icon: "🍃" },
  { name: "TypeScript", badge: "Advanced", category: "language", icon: "🔷" },
  { name: "JavaScript", badge: "Expert", category: "language", icon: "🟡" },
  { name: "Tailwind CSS", badge: "Expert", category: "frontend", icon: "🎨" },
  { name: "PostgreSQL", badge: "Intermediate", category: "database", icon: "🐘" },
  { name: "Redis", badge: "Intermediate", category: "database", icon: "🔴" },
  { name: "Docker", badge: "Intermediate", category: "devops", icon: "🐳" },
  { name: "AWS", badge: "Intermediate", category: "devops", icon: "☁️" },
  { name: "GraphQL", badge: "Advanced", category: "backend", icon: "🔺" },
  { name: "REST APIs", badge: "Expert", category: "backend", icon: "🔗" },
  { name: "Git & GitHub", badge: "Expert", category: "tools", icon: "🐙" },
  { name: "Figma", badge: "Intermediate", category: "tools", icon: "🎭" },
  { name: "Redux Toolkit", badge: "Advanced", category: "frontend", icon: "🟣" },
  { name: "Socket.io", badge: "Advanced", category: "backend", icon: "🔌" },
]

export const projects = [
  {
    id: 1,
    title: "Henry Clark - Portfolio",
    description: "A sleek personal portfolio website showcasing projects, skills, and experience with an elegant design and smooth user interactions.",
    image: "https://res.cloudinary.com/dj0deiybu/image/upload/v1774290978/Thumbnail_cthiwf.jpg",
    tags: ["Vite", "React", "JavaScript", "TailwindCSS"],
    platform: "web",
    type: "frontend",
    liveUrl: "https://portfolio-hc-app.vercel.app/",
    githubUrl: "https://github.com/MohamedAbobakr12/Portfolio",
    featured: true,
    slug: "henry-clark-portfolio",
    stats: { projects: "10+", skills: "15+", responsive: "100%" },
  },
  {
    id: 2,
    title: "Xora | SaaS Landing Page",
    description: "A modern, fully responsive SaaS landing page featuring smooth animations, clean UI components, and a professional layout designed to showcase product features and drive user conversions.",
    image: "https://res.cloudinary.com/dj0deiybu/image/upload/v1774285742/Thumbnail_ah3fpw.jpg",
    tags: ["Vite", "React", "JavaScript", "TailwindCSS"],
    platform: "web",
    type: "frontend",
    liveUrl: "https://xora-app.vercel.app/",
    githubUrl: "https://github.com/MohamedAbobakr12/Xora",
    featured: true,
    slug: "xora-saas-landing-page",
    stats: { sections: "10+", animations: "Smooth", responsive: "100%" },
  },
  {
    id: 3,
    title: "Space Portfolio",
    description: "A visually immersive fullstack developer portfolio built with Next.js, featuring a space-themed design, animated UI, and a comprehensive showcase of skills spanning frontend, backend, mobile, and DevOps technologies.",
    image: "https://res.cloudinary.com/dj0deiybu/image/upload/v1774291838/Thumbnail_gereei.jpg",
    tags: ["Next.js", "React", "TypeScript", "TailwindCSS"],
    platform: "web",
    type: "frontend",
    liveUrl: "https://space-portfolio-next.vercel.app/",
    githubUrl: "https://github.com/MohamedAbobakr12/Space-Portfolio",
    featured: true,
    slug: "space-portfolio",
    stats: { skills: "20+", projects: "3+", stack: "Fullstack" },
  },
  {
    id: 4,
    title: "Nike",
    description: "A pixel-perfect Nike landing page clone built with a modern frontend stack, featuring a clean product showcase, responsive design, and smooth UI interactions inspired by Nike's official brand aesthetic.",
    image: "https://res.cloudinary.com/dj0deiybu/image/upload/v1774292734/Thumbnail_q0ixzl.jpg",
    tags: ["Vite", "React", "JavaScript", "TailwindCSS"],
    platform: "web",
    type: "frontend",
    liveUrl: "https://nike-three-virid.vercel.app/",
    githubUrl: "https://github.com/MohamedAbobakr12/Nike",
    featured: false,
    slug: "nike",
    stats: { doctors: "200+", patients: "3K+", calls: "50K+" },
  },
  {
    id: 5,
    title: "E-Commerce Bike",
    description: "A fully responsive e-commerce bike store featuring product showcases, categories, accessories, and a modern UI with smooth navigation built for cycling enthusiasts.",
    image: "https://res.cloudinary.com/dj0deiybu/image/upload/v1774294632/Thumbnail_nkrjxh.jpg",
    tags: ["Next.js", "React", "JavaScript", "TailwindCSS"],
    platform: "web",
    type: "frontend",
    liveUrl: "https://e-bike-rose.vercel.app/",
    githubUrl: "https://github.com/MohamedAbobakr12/E-Bike",
    featured: false,
    slug: "ecommerce-bike",
    stats: { products: "20+", categories: "4+", speed: "45 KM/H" },
  },
  {
    id: 6,
    title: "Hubble - Landing Page SaaS",
    description: "A professional SaaS landing page for an ecommerce management platform, featuring CRM highlights, client testimonials, team section, blog, and FAQ — all wrapped in a clean and modern UI.",
    image: "https://res.cloudinary.com/dj0deiybu/image/upload/v1774296717/Thumbnail_nvutft.jpg",
    tags: ["Next.js", "React", "JavaScript", "TailwindCSS"],
    platform: "web",
    type: "frontend",
    liveUrl: "https://hubble-puce.vercel.app/",
    githubUrl: "https://github.com/MohamedAbobakr12/Hubble",
    featured: false,
    slug: "hubble-landing-page",
    stats: { companies: "100+", integrations: "10+", sections: "8+" },
  },
  {
    id: 7,
    title: "Crypto App",
    description: "A modern crypto investment platform landing page featuring token listings, pricing plans, team section, and partner integrations — designed to build trust and drive user onboarding in the crypto space.",
    image: "https://res.cloudinary.com/dj0deiybu/image/upload/v1774303062/Thumbnail_ct1sjy.jpg",
    tags: ["Next.js", "React", "JavaScript", "TailwindCSS"],
    platform: "web",
    type: "frontend",
    liveUrl: "https://crypto-app-beta-lemon.vercel.app/",
    githubUrl: "https://github.com/MohamedAbobakr12/Crypto-App",
    featured: false,
    slug: "crypto-app",
    stats: { tokens: "128+", partners: "5+", plans: "3" },
  },
  {
    id: 8,
    title: "Movies App",
    description: "A dynamic movie discovery app powered by a live movies API, featuring trending movies, real-time search, ratings, and a sleek dark-themed UI for an immersive browsing experience.",
    image: "https://res.cloudinary.com/dj0deiybu/image/upload/v1774311964/Thumbnail_smnvph.jpg",
    tags: ["Vite", "React", "JavaScript", "TailwindCSS"],
    platform: "web",
    type: "frontend",
    liveUrl: "https://movies-app-live.vercel.app/",
    githubUrl: "https://github.com/MohamedAbobakr12/Movie-App",
    featured: false,
    slug: "movies-app",
    stats: { movies: "1000+", trending: "Real-time", search: "Instant" },
  },
]

export const experience = [
  {
    year: "2025 – Present",
    role: "Junior MERN Stack Developer",
    company: "Freelance · Remote",
    description: "Building end-to-end web applications for clients worldwide. Delivered 15+ projects with a 100% client satisfaction rate.",
    skills: ["Next.js", "React", "Node.js", "Expess.js", "MongoDB"],
    type: "work",
  },
  {
    year: "2024 – 2025",
    role: "Frontend Developer",
    company: "StartupHub",
    description: "Built pixel-perfect UIs from Figma designs, optimized performance by 60%, and shipped features weekly.",
    skills: ["HTML", "CSS", "TailwindCSS","JavaScript", "React"],
    type: "work",
  },
    {
    year: "2022-2026",
    role: "College Student",
    company: "New Cairo Technological University",
    description: "Studied Computer Science fundamentals covering algorithms, data structures, AI, and mobile development. Completed various academic projects across multiple programming languages.",
    skills: ["Python", "Java", "C", "C++", "C#", "Databases", "DSA", "AI", "OS", "Flutter", "Mobile Programming"],
    type: "education",
  },
  {
    year: "2019-2022",
    role: "Student",
    company: "Misr International Computer & AI",
    description: "Studied Computer Science fundamentals, algorithms, and software engineering principles. Built several academic projects using Java and SQL.",
    skills: ["Java", "OOP", "SQL", "PL_SQL"],
    type: "education",
  },
]

export const services = [
  {
    title: "Full-Stack Web Apps",
    description: "End-to-end MERN stack applications, from database design to deployment.",
    icon: "🖥️",
    tag: "🌐",
  },
  {
    title: "API Development",
    description: "Scalable REST or GraphQL APIs with authentication, rate limiting, and docs.",
    icon: "🔌",
    tag: "🔧",
  },
  {
    title: "Performance Optimization",
    description: "Speed audit and optimization for existing React or Node.js applications.",
    icon: "⚡",
    tag: "📈",
  },
  {
    title: "SaaS Development",
    description: "Complete SaaS platforms with subscriptions, dashboards, and multi-tenancy.",
    icon: "🚀",
    tag: "💡",
  },
]
